[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = "0.20.0"
percent-encoding = "2.3.1"
ropey = "1.6.1"
dashmap = "5.5.3"
url = "2.5.0"
chumsky = "1.0.0-alpha.6"

[dependencies.tokio]
version = "1.36.0"
features = ["full"]
