[package]
name = "gitignore-ultimate-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = "0.20.0"
dashmap = "5.5.3"
url = "2.5.0"
chumsky = "1.0.0-alpha.6"
lsp-workspace = { path = "../../packages/lsp-workspace" }

[dependencies.tokio]
version = "1.36.0"
features = ["full"]
